// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/zlog-fun/ysword"
	"ysword_layout/bootstrap"
	"ysword_layout/internal/biz"
	"ysword_layout/internal/repo"
	"ysword_layout/internal/router"
	"ysword_layout/internal/service"
)

// Injectors from wire.go:

func InitializeApp(bcf bootstrap.AppConfig) (*ysword.App, func(), error) {
	cache, err := repo.NewData()
	if err != nil {
		return nil, nil, err
	}
	blogRepo := repo.NewBlogRepo(cache)
	blog := biz.NewBlog(blogRepo)
	blogService := service.NewBlogService(blog)
	v := router.New(blogService)
	app := newApp(bcf, v)
	return app, func() {
	}, nil
}
